version: '2'
services:
  storage-server:
    build:
      context: cmd/storage
      dockerfile: "Dockerfile"
    ports:
      - "9100:9100"

  ingester-server:
    depends_on:
      - storage-server
    build:
      context: cmd/ingester
      dockerfile: "Dockerfile"
    ports:
      - "9101:9101"
    environment:
      - STORAGE_HOST=storage-server:9100
