// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpsertRequest struct {
	Table                string    `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Records              []*Record `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpsertRequest) Reset()         { *m = UpsertRequest{} }
func (m *UpsertRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertRequest) ProtoMessage()    {}
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *UpsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertRequest.Unmarshal(m, b)
}
func (m *UpsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertRequest.Marshal(b, m, deterministic)
}
func (m *UpsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertRequest.Merge(m, src)
}
func (m *UpsertRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertRequest.Size(m)
}
func (m *UpsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertRequest proto.InternalMessageInfo

func (m *UpsertRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *UpsertRequest) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type Record struct {
	Key                  *Field   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Fields               []*Field `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetKey() *Field {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Record) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Field struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UpsertReply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertReply) Reset()         { *m = UpsertReply{} }
func (m *UpsertReply) String() string { return proto.CompactTextString(m) }
func (*UpsertReply) ProtoMessage()    {}
func (*UpsertReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *UpsertReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertReply.Unmarshal(m, b)
}
func (m *UpsertReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertReply.Marshal(b, m, deterministic)
}
func (m *UpsertReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertReply.Merge(m, src)
}
func (m *UpsertReply) XXX_Size() int {
	return xxx_messageInfo_UpsertReply.Size(m)
}
func (m *UpsertReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertReply proto.InternalMessageInfo

func (m *UpsertReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpsertReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*UpsertRequest)(nil), "proto.UpsertRequest")
	proto.RegisterType((*Record)(nil), "proto.Record")
	proto.RegisterType((*Field)(nil), "proto.Field")
	proto.RegisterType((*UpsertReply)(nil), "proto.UpsertReply")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0xb5, 0x5d, 0x77, 0x8b, 0xb3, 0x2e, 0xc8, 0xd0, 0xc3, 0xe2, 0x41, 0x4a, 0x10, 0xec, 0xa9,
	0xe0, 0xd6, 0xbb, 0x37, 0x8f, 0x3d, 0x44, 0xfc, 0x80, 0x6d, 0x77, 0x2c, 0x62, 0x6a, 0x62, 0x92,
	0x0a, 0xfb, 0xf7, 0x92, 0x49, 0x72, 0xd8, 0x9e, 0x32, 0xef, 0xbd, 0x79, 0x8f, 0x97, 0x81, 0xc6,
	0x79, 0x6d, 0xfb, 0x23, 0x6d, 0x8c, 0xd5, 0x5e, 0x63, 0xc9, 0x8f, 0xd8, 0x41, 0xf3, 0x61, 0x1c,
	0x59, 0x2f, 0xe9, 0xf7, 0x4c, 0xce, 0xe3, 0x12, 0x4a, 0xdf, 0xef, 0x15, 0xb5, 0xb3, 0xd5, 0x6c,
	0x7d, 0x23, 0x23, 0xc0, 0x27, 0x58, 0x58, 0x3a, 0x68, 0x3b, 0xb8, 0x76, 0xbe, 0x2a, 0xd6, 0x75,
	0xd7, 0xc4, 0x98, 0x8d, 0x64, 0x56, 0x66, 0x55, 0xec, 0xa0, 0x8a, 0x14, 0x3e, 0x40, 0xf1, 0x4d,
	0x23, 0xc7, 0xd4, 0xdd, 0x6d, 0x5a, 0x7f, 0xfb, 0x22, 0x35, 0xc8, 0x20, 0xe0, 0x23, 0x54, 0x9f,
	0x01, 0xe5, 0xc4, 0xe9, 0x4a, 0xd2, 0xc4, 0x33, 0x94, 0x4c, 0x20, 0xc2, 0xf5, 0x4f, 0x7f, 0xca,
	0xb5, 0x78, 0x0e, 0x5d, 0xff, 0x7a, 0x75, 0xa6, 0x76, 0x1e, 0xbb, 0x32, 0x10, 0x5b, 0xa8, 0xf3,
	0x97, 0x8c, 0x1a, 0x83, 0xf1, 0xa0, 0x87, 0x68, 0x2c, 0x25, 0xcf, 0x78, 0x07, 0xc5, 0xc9, 0x1d,
	0x93, 0x2d, 0x8c, 0xdd, 0x2b, 0x2c, 0xde, 0xe3, 0x7d, 0xf0, 0x05, 0xaa, 0xe8, 0xc7, 0x65, 0xaa,
	0x34, 0xb9, 0xd0, 0x3d, 0x5e, 0xb0, 0x46, 0x8d, 0xe2, 0x6a, 0x5f, 0x31, 0xb9, 0xfd, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0xbd, 0x88, 0x51, 0x69, 0x67, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	Upsert(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertReply, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) Upsert(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertReply, error) {
	out := new(UpsertReply)
	err := c.cc.Invoke(ctx, "/proto.Storage/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	Upsert(context.Context, *UpsertRequest) (*UpsertReply, error)
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Storage/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Upsert(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _Storage_Upsert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
